steps:

# Initialise Terraform
- task: TerraformCLI@0
  displayName: 'Terraform Initialise'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendType: 'azurerm'
    backendServiceArm: '$(backendServiceArm)'
    ensureBackend: true
    backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
    backendAzureRmResourceGroupLocation: '$(backendAzureRmResourceGroupLocation)'
    backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
    backendAzureRmContainerName: '$(backendAzureRmContainerName)'
    backendAzureRmKey: '$(backendAzureRmKey)'