steps:

# Terraform command
- task: TerraformCLI@0
  condition: ${{ parameters.condition }}
  name: '${{ parameters.name }}'
  displayName: '${{ parameters.displayName }}'
  inputs:
    command: '${{ parameters.command }}'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: '$(backendServiceArm)'
    publishPlanResults: '${{ parameters.publishPlanResults }}'
    commandOptions: '${{ parameters.commandOptions }}'
  env:
    AZDO_PERSONAL_ACCESS_TOKEN: $(org_pat)
    AZDO_ORG_SERVICE_URL: $(org_url)
    GITHUB_TOKEN: $(github_token)