steps:
   
# Install Go
- task: GoTool@0
  displayName: 'Go Install'
  inputs:
    version: '1.18'

# Create test module
- task: Go@0
  displayName: 'Create test module'  
  inputs:
    command: 'custom'
    customCommand: 'mod'
    arguments: 'init module'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tests'

# Add module dependencies
- task: Go@0
  displayName: 'Get test dependencies'
  inputs:
    command: 'custom'
    customCommand: 'mod'
    arguments: 'tidy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tests'

