steps:

# Publish artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    targetPath: '$(Pipeline.Workspace)/Output'
    artifact: '${{ parameters.artifact }}'
    publishLocation: 'pipeline'