steps:

# Evaluate Terraform Plan with OPA
- bash: |
    # Set working directory
    cd $(System.DefaultWorkingDirectory)
    # Generate JSON plan
    terraform show -json $(Pipeline.Workspace)/Output/apply_terraform.tfplan >$(System.ArtifactsDirectory)/plan.json
    # Evaluate plan with OPA
    opa exec --decision terraform/analysis/authz --bundle policy/ $(System.ArtifactsDirectory)/plan.json > $(Pipeline.Workspace)/Output/opa_decision.json
    opa exec --decision terraform/analysis/score --bundle policy/ $(System.ArtifactsDirectory)/plan.json > $(Pipeline.Workspace)/Output/opa_score.json
  name: 'OPADecision'
  displayName: 'Evaluate Terraform Plan with OPA'