steps:

# Scan Terraform Plan with Regula
- bash: |
    # Set working directory
    cd $(System.DefaultWorkingDirectory)
    # Generate JSON plan
    terraform show -json $(Pipeline.Workspace)/Evaluate/apply_terraform.tfplan >$(System.ArtifactsDirectory)/plan.json
    # Scan plan
    regula run $(System.ArtifactsDirectory)/plan.json -s critical
  name: 'RegulaScan'
  displayName: 'Scan Terraform Plan with Regula'