steps:

# Select workspace (if exists)
- task: TerraformCLI@0
  displayName: 'Terraform Workspace select'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    command: 'workspace'
    workspaceSubCommand: 'select'
    workspaceName: $(Environment)