steps:

# Packer steps
- template: ../../Tasks/packer/packer_install.yml
- template: ../../Tasks/pwsh/create_runner_image.yml
  parameters:
    imageType: ${{ parameters.imageType }}
    platform: ${{ parameters.platform }}
    location: ${{ parameters.location }}
    imageResourceGroupName: ${{ parameters.imageResourceGroupName }}
- template: ../../Tasks/pwsh/cleanup_runner_image.yml
  parameters:
    imageResourceGroupName: ${{ parameters.imageResourceGroupName }}