steps:

# Login to Azure
- bash: |
    # Login to Azure
    az login --service-principal -u $SERVICEPRINCIPALID -p $SERVICEPRINCIPALKEY --tenant $(TenantID)
    # Select subscription
    az account set --subscription $(SubscriptionId)
  name: 'AzureLogin'
  displayName: 'Authenticate with Azure'
  env:
    SERVICEPRINCIPALID: $(ServicePrincipalId)
    SERVICEPRINCIPALKEY: $(ServicePrincipalKey)