steps:

# Login to Azure
- pwsh: |
    # Login to Azure
    az login --service-principal -u $env:SERVICEPRINCIPALID -p $env:SERVICEPRINCIPALKEY --tenant $(TenantID)
    
    # Select subscription
    az account set --subscription $(SubscriptionId)

    # Variables
    $Command = "${{ parameters.command }}"
    $Destroy = "${{ parameters.destroy }}"
    
    # Bicep Subscription Command
    az deployment sub $Command -f "${{ parameters.resources_file }}_incremental.bicep" --location "${{ parameters.location }}" | Tee-Object -Variable Result

    # Remove Resource Group if variable is true
    if ($Destroy){
      az group delete --name $ResourceGroupName --yes
    }

  name: 'AzureBicep'
  displayName: 'Bicep Deployment'
  env:
    SERVICEPRINCIPALID: $(ServicePrincipalId)
    SERVICEPRINCIPALKEY: $(ServicePrincipalKey)