steps:

# Login to Azure
- pwsh: |
    # Login to Azure
    az login --service-principal -u $env:SERVICEPRINCIPALID -p $env:SERVICEPRINCIPALKEY --tenant $(TenantID)
    
    # Select subscription
    az account set --subscription $(SubscriptionId)

    # Variables
    $Command = "${{ parameters.command }}"
    $Destroy = "${{ parameters.destroy }}"
    
    # Bicep Subscription Command
    az deployment sub $Command -f "${{ parameters.resource_group_file }}" --location "${{ parameters.location }}" | Tee-Object -Variable Result

    # Get Resource Group Name
    $JSON = $Result | ConvertFrom-Json -Depth 10
    $Split = $json.properties.outputResources.id.split("/")
    $ResourceGroupName = $Split[-1]

    # Bicep Group Command
    az deployment group $Command -f "${{ parameters.resources_file }}" --resource-group $ResourceGroupName --mode "Complete"

    # Remove Resource Group if variable is true
    if ($Destroy){
      az group delete --name $ResourceGroupName --yes
    }

  name: 'AzureBicep'
  displayName: 'Bicep Deployment'
  env:
    SERVICEPRINCIPALID: $(ServicePrincipalId)
    SERVICEPRINCIPALKEY: $(ServicePrincipalKey)