steps:

# Login to Azure
- bash: |
    # Login to Azure
    az login --service-principal -u $SERVICEPRINCIPALID -p $SERVICEPRINCIPALKEY --tenant $(TenantID)
    # Select subscription
    az account set --subscription $(SubscriptionId)
    # Deploy Bicep
    az deployment sub ${{ parameters.command }} -f "${{ parameters.file }}" --location "${{ parameters.location }}"
  name: 'AzureBicep'
  displayName: 'Azure Bicep'
  env:
    SERVICEPRINCIPALID: $(ServicePrincipalId)
    SERVICEPRINCIPALKEY: $(ServicePrincipalKey)