stages:
- stage: Integration
  condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  - job: Test
    displayName: 'Test'
    continueOnError: false
    steps:

    # Terraform install step
    - template: ../Steps/terraform_install.yml

    # Go steps
    - template: ../Steps/go.yml
      parameters:
        arguments: '-v integration_test.go'